# Теория вероятностей и математическая статистика
## Домашнее задание по уроку 6

In [1]:
import numpy as np
import pandas as pd

### Задача 1

Даны значения величины заработной платы заемщиков банка (`salary`) и значения их поведенческого кредитного скоринга (`scoring`):
```
salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]
```
1. Найдите ковариацию этих двух величин: сначала без использования специальных функций, а затем с помощью функции `numpy.cov`. Полученные значения должны быть равны.
2. Найдите коэффициент корреляции Пирсона: с помощью ковариации и средних квадратических отклонений двух признаков, а затем с помощью специальных функций из библиотек `numpy` и `pandas`.

#### Решение
##### 1)
Обозначим случайную величину `X` как salary и `Y` как scoring:

In [37]:
client = pd.DataFrame({
    'salary' : [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
    'scoring' : [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]
},  columns=['salary','scoring'])

X = client['salary']
Y = client['scoring']

Посчитаем среднее для двух величин

In [38]:
MX = X.mean()
MY = Y.mean()

Вычислим ковариацию по форумуле:
$$\operatorname{cov}(X, Y) = M(XY) - M(X) \: M(Y).$$

In [49]:
cov = (X * Y).mean() - MX * MY
cov

9157.839999999997

In [50]:
cov = ((X - MX) * (Y - MY)).sum() / (X.shape[0] - 1)
cov

10175.37777777778

Либо воспользуемся `numpy.cov()`:

In [48]:
cov = np.cov(X,Y)
cov

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

В данном случае полученные значения не равны. Грешу на малую выборку

##### 2)
Найдем коэффициент корреляции Пирсона.
Ручками:

In [47]:
corr = cov / (X.std() * Y.std())
corr

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

Через функцию `corr()` библиотеки `pandas.DataFrame`:

In [45]:
client[['salary','scoring']].corr()

salary  scoring
salary   1.00000  0.88749
scoring  0.88749  1.00000

Через функцию `corrcoef()` библиотеки `numpy`:

In [44]:
np.corrcoef(X, Y)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

### Задача 2

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:
```
131, 125, 115, 122, 131, 115, 107, 99, 125, 111
```
Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

#### Решение
Высчитаем их среднее и несмещённую оценку для среднего квадратического отклонения в выборке:

In [26]:
X = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
m = X.mean()
s = X.std(ddof=1)
n = X.shape[0]

Найдем нужный квантиль из таблицы. В нашем случае он равен 2.2622

In [28]:
t = 2.2622

In [29]:
(m - t * s / np.sqrt(n), m + t * s / np.sqrt(n))

(110.55594079648245, 125.64405920351754)

### Задача 3

Известно, что рост футболистов в сборной распределен нормально с известной дисперсией 25. На выборке объёма 27 выборочное среднее составило 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

#### Решение
Раз дисперсия известна и надежность доверительного интервала равна 0.95, мы можем воспользоваться правилом двух сигм:
$$\left( a - 2\sigma, a + 2\sigma \right)$$
где $a=174.2, \sigma = \sqrt{\dfrac{D(X)}{n}}$

In [32]:
a = 174.2
D = 25
n = 27
sig = np.sqrt(D/n)
(a - 2*sig, a + 2*sig)

(172.27549910270125, 176.12450089729873)

### Задача 4

Выберите тему для проектной работы по курсу Теории вероятностей и математической статистики и напишите ее в комментарии к Практическому заданию.